### ISSUE TITLE
Enable HTTP2 for server

### ISSUE THREAD

**Issue by TimvdLippe** [Mentoraat/plannings-tool-server#25]
Would be nice to have the performance improvements of HTTP2

http://stackoverflow.com/questions/29389690/enable-http2-with-maven-jetty-plugin/29429764#29429764

http://www.eclipse.org/jetty/documentation/current/http2.html

https://www.eclipse.org/jetty/documentation/9.3.0.v20150612/jetty-maven-plugin.html

**Comment by jwgmeligmeyling** [comment]
As you're probably running an embedded jetty container, this is probably a better reference: http://stackoverflow.com/questions/31642015/embedded-jetty-http-2-not-working-with-firefox-chrome-but-seems-ok-with-safari .

**Comment by jwgmeligmeyling** [comment]
Question that pops up though: what are the benefits of HTTP/2 beyond a reverse proxy / loadbalancer as nginx?

**Comment by TimvdLippe** [comment]
#26 is required for this issue. We have to investigate the performance gains when enabling HTTP2.
