### ISSUE TITLE
Use HTTPS to encrypt communication

### ISSUE THREAD

**Issue by TimvdLippe** [Mentoraat/plannings-tool-server#26]
- [ ] Get a certificate of Let's Encrypt
- [ ] Configure Jetty to use the https

**Comment by TimvdLippe** [comment]
http://roobert.github.io/2015/12/06/LetsEncrypt-NGiNX-Quick-Start/
https://johnmaguire.me/2015/12/configuring-nginx-lets-encrypt-automatic-renewal/
https://davidzych.com/setting-up-ssl-with-lets-encrypt-on-ubuntu-and-nginx/

https://www.youtube.com/watch?v=pgBQn_z3zRE which shows https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by GijsWeterings** [comment]
bump

**Comment by TimvdLippe** [comment]
Will take this ticket over to fiddle with SSL.

**Comment by GijsWeterings** [comment]
got it!
