### ISSUE TITLE
Verify user enrolling in courses on signup

### ISSUE THREAD

**Issue by GijsWeterings** [Mentoraat/plannings-tool-server#44]

**Comment by TimvdLippe** [comment]
Yes this is performed (see https://github.com/Mentoraat/plannings-tool-server/blob/master/src/main/java/nl/tudelft/planningstool/api/v1/AuthenticationAPI.java#L64) however, I spotted an error: there is no default user role. This should be STUDENT by default.

**Comment by TimvdLippe** [comment]
Has been fixed in the mean time.
